### ISSUE TITLE
It's working! \o/

### ISSUE THREAD

**Issue by rubyFeedback** [mvz/gir_ffi-gtk4#37]
Hey there Matijs,

I just github cloned this repository, and tested:

   gir_ffi-gtk/examples/ruby 03_upgraded_hello_world.rb 

And it is working! \o/

I have not yet tested the other .rb files there but I assume they probably
work. I myself am still using mostly ruby-gtk3, but it is nice to eventually
have options available for ruby-gtk4. At any rate, over the holidays I tend
to be a bit less active, so happy new year transition to you and your fellow
like minded people.

(I'll close this issue here to avoid spamming the issue tracker with open
issues, so this was really just meant to give you quick feedback that this
indeed appears to be working.)

**Comment by mvz** [comment]
Happy holidays!
